
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    
image: gitpod/workspace-postgres
tasks:
  - name: Initialize & Configure AWS
    command: bash $GITPOD_REPO_ROOT/configure_aws_with_gitpod.sh

